// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A once-per-thread pause that accepts a later explicit user message.
 */
export type ContextPause = { usedTokens: number, contextWindow: number, thresholdPercent: number, };
