// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Runtime accounting against the usable context limit.
 */
export type ContextWindowUsage = { usedTokens: number, contextWindow: number, };
