// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Pauses once per thread until explicit user input.
 */
export type ContextPause = { usedTokens: number, contextWindow: number, thresholdPercent: number, };
